# ============================
# EAGT Config (SEMAINE dataset)
# ============================

seed: 1337
device: cuda

data:
  dataset: semaine
  root: /datasets/SEMAINE
  split_csv: /datasets/SEMAINE/metadata.csv   # metadata file for sessions
  face_fps: 25
  audio_sr: 16000
  window_sec: 2.0
  stride_sec: 1.0
  classes: [anger, fear, sadness, happiness, neutral]  # emotions available in SEMAINE

preprocess:
  face_detector: mediapipe
  face_size: 112
  augment: false

model:
  vision_backbone: resnet18
  audio_backbone: wav2vec2
  hidden_dim: 512
  lstm_layers: 3
  dropout: 0.4

train:
  batch_size: 4
  epochs: 12
  lr: 2e-4
  weight_decay: 1e-5
  warmup_steps: 200
  grad_clip: 1.0
  ckpt_dir: checkpoints/semaine
  log_interval: 5

genai:
  model_name: gpt2
  max_new_tokens: 200
  temperature: 0.7
  top_p: 0.9
  rag_corpus_dir: ./rag_corpus
  use_rag: true

server:
  host: 0.0.0.0
  port: 8001
